# Generated by Django 5.1.3 on 2024-12-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("merchant", "0002_activitylog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merchant",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="merchant",
            name="phone",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
