# Generated by Django 5.1.4 on 2024-12-11 15:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "payment_gateway",
            "0002_paymentgateway_created_at_paymentgateway_description_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("invoice_id", models.CharField(max_length=50, unique=True)),
                ("merchant_id", models.CharField(max_length=100)),
                ("merchant_webhook_url", models.URLField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("username", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "payment_method",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "payment_method_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="paymentgateway",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name="PaymentTransaction",
        ),
    ]
