# Generated by Django 5.1.3 on 2024-12-12 04:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment_gateway", "0006_remove_invoice_merchant_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentgateway",
            name="input_fields",
            field=models.JSONField(default=dict, null=True),
        ),
    ]
