# Generated by Django 5.1.3 on 2024-12-12 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment_gateway", "0007_alter_paymentgateway_input_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="merchant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="payment_gateway.merchant",
            ),
        ),
        migrations.AlterField(
            model_name="merchant",
            name="merchant_id",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
