# Generated by Django 5.1.3 on 2024-12-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment_gateway", "0008_alter_invoice_merchant_alter_merchant_merchant_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="payment_data",
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name="paymentgateway",
            name="webhook_url",
            field=models.URLField(default="www.example.url"),
        ),
    ]
